# .github/workflows/keep-alive.yml
name: Keep Render Alive

on:
  schedule:
    # every 10 minutes
    - cron:  '*/10 * * * *'
  workflow_dispatch:   # allows you to trigger it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: |
          curl -fsS https://james-warriner-api.onrender.com/api/ping || true
